export const feedIcon = require('./feed.png')
export const activitiesIcon = require('./activities.png')
export const profileIcon = require('./profile.png')
export const progressIcon = require('./progress.png')
export const backIcon = require('./back.png')
export const uploadIcon = require('./upload.png')
export const completedIcon = require('./completed.png')
export const virusIcon = require('./virus.png')
